global:
  imagePullSecrets:
    - ghcr-secret

gateway:
  replicas: 1
  image: ghcr.io/deldore/quickticket-gateway:15fd830bd12d01c4247f70ccfb119c9c6ee608aa
  version: "v2"
  timeoutMs: "5000"

events:
  replicas: 1
  image: ghcr.io/deldore/quickticket-events:15fd830bd12d01c4247f70ccfb119c9c6ee608aa
  db:
    host: postgres
    port: 5432
    name: quickticket
    user: quickticket
    password: quickticket
  redis:
    host: redis
    port: "6379"
  dbMaxConns: "10"
  redisTimeoutMs: "1000"
  reservationTtl: "300"

payments:
  replicas: 1
  image: ghcr.io/deldore/quickticket-payments:15fd830bd12d01c4247f70ccfb119c9c6ee608aa
  failureRate: "0.0"
  latencyMs: "0"
